spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kay2xq/config-repo.git
          username: kay2xq
          password: 123njdwjsmn456
  rabbitmq:
    host: 192.168.1.113
    port: 5672
    username: kay
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"